SistemaCoder/profesores/urls.py
from django.urls import path
from . import views


app_name = 'profesor'
urlpatterns = [
    path('', views.index, name='index' ),
    path('formulario', views.formulario, name="formulario"),
    path(
        '<int:profesor_id>', 
        views.detalle,
        name='detalle' )
]

SistemaCoder/sistemacoder/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    path('profesores/', include('profesores.urls'))
    
]

SistemaCoder/profesores/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Curso(models.Model):
    nombre = models.CharField(max_length=30)
    camada = models.IntegerField()
    creacion = models.DateTimeField(default=timezone.now) 
    
    def __str__(self):
        return self.nombre
    
    
    
class Profesor(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=30)
    profesion = models.CharField(max_length=50)
    email = models.EmailField()
    fechaNacimiento = models.DateField()
    curso = models.ForeignKey( Curso, on_delete=models.DO_NOTHING )
    
    def __str__(self):
        return ( self.nombre +" " + self.apellido )
    
    

SistemaCoder/profesores/forms.py
from . import models
from django.forms import ModelForm

class ProfesorForm(ModelForm):
    class Meta:
        model = models.Profesor
        fields = ['nombre', 'apellido', 'profesion', 'email', 'fechaNacimiento', 'curso' ]
        

SistemaCoder/profesores/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ProfesorForm
from .models import Profesor

# Create your views here.

def index(request):
    profesores = Profesor.objects.all()
#    profesores = Profesor.objects.filter(curso="python")  
#    profesores = Profesor.objects.get(curso='python')
#    print(profesores)
    return render(
        request, 
        'baseProf.html', 
        context= {'profesores': profesores } 
    )

    #return HttpResponse(profesores[0].nombre)
    
def detalle(request, profesor_id):
        profesor = get_object_or_404(Profesor, id=profesor_id)
    
        return render(
            request,
            'detalle.html', 
            context= { 'profesor': profesor } )
    
    
def formulario(request):
    if request.method == 'POST':
        form = ProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/profesores')
    else:
        form = ProfesorForm()
         
    
    return render(
        request,
        'profesor_form.html',
        {'form': form} 
    )

SistemaCoder/sistemacoder/views.py
from django.shortcuts import render

def inicio(request):
    return render(
        request,
        'inicio.html',
    )

SistemaCoder/profesores/templates/baseProf.html
{% extends 'base.html' %}

{%block content%}

<h1>Profesores</h1>

<a href="{% url 'profesor:formulario' %}">Agregar</a>

 

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Profesion</th>
            <th>e-mail</th>           
            <th>Curso</th>           
        </tr> 
    </thead>
    
    <body>

        {% for profesor in profesores %}
        
        <tr>
            <td>
                <a href="{% url 'profesor:detalle' profesor.id %}">
                    {{profesor.nombre}}
                </a>
            </td>
            <td>{{profesor.apellido}}</td>
            <td>{{profesor.profesion}}</td>
            <td>{{profesor.email}}</td>
            <td>{{profesor.curso}}</td>
        </tr>
        
        {% endfor %} 
        
    </body>
    
</table>

{%endblock content%}

SistemaCoder/profesores/templates/detalle.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5>{{profesor.nombre}}</h5>
    <p>{{profesor.profesion}}</p>
    <p>{{profesor.email}}</p>
    <p>{{profesor.fechaNacimiento</p>
    <p>{{profesor.curso}}</p>
</div>
{% endblock content %}

SistemaCoder/profesores/templates/profesor_form.html
{% extends 'base.html' %}

{% block content %}
<form 
    
        action="{% url 'profesor:formulario' %}" 
        method='post'>
        {% csrf_token %}
        {{ form }}
    
    <input type="submit" value="Envia"/>

</form>
     

{% endblock content %}
 

SistemaCoder/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SistemaCoder2023</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    
        <div class="container-fluid">
          {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profesor:index' %}">Profesores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Cursos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Alumnos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Entregables</a>
              </li>
              {% comment %} <li class="Alumnos">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
      </nav>
    <p> </p>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div> 
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>

</html>

SistemaCoder/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

SistemaCoder/templates/django/forms/widgets/input.html
<input 
    class="form-control {{ widget.attrs.class}}" 
    type="{{ widget.type }}" 
    name="{{ widget.name }}"
    {% if widget.value != None %} 
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

SistemaCoder/templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>

SistemaCoder/templates/form_snippet.html
{% for field in form %}
<div class="mb-3">
    {{ field.label_tag }} {{ field }}
    <div class="invalid-feedback">
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
    </div>
</div>

{% endfor %}

SistemaCoder/templates/inicio.html
{% extends 'base.html' %}

{% block content %}
    hola coder house !!!

{% endblock content %}